<?php

$messages = array();
$messages['lastlogin_info'] = 'Dernière session ouverte $date depuis l\'adresse IP $from $geo. <a href="$more">[+]</a>';
$messages['noinfo'] = 'Informations non disponibles.';
$messages['timeout'] = 'Voir les informations de la dernière session';

$labels = array();
$labels['lastlogin'] = 'Dernières connections';
$labels['info'] = 'Information';
$labels['conf'] = 'Paramètres';
$labels['fornseconds'] = 'for $n seconds';
$labels['recentactivity'] = 'Activité récente:';
$labels['ip'] = 'adresse IP';
$labels['hostname'] = 'Nom';
$labels['timestamp'] = 'Date/Heure';
$labels['today'] = 'aujourd\'hui';
$labels['yesterday'] = 'hier';
$labels['geoip_license'] = 'Les données géographiques fournies ici sont basées sur les bases de données gratuites GeoLite2 créées par MaxMind, disponibles sur <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
$labels['ua'] = 'User Agent';

